name: Daily Job

on:
  schedule:
    - cron: "0 8,20 * * *"
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y yt-dlp sed nmap

    - name: Pull Remote Changes
      run: |
        cd $GITHUB_WORKSPACE/speedtest
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git stash || true  # Stash any local changes if they exist
        git pull origin main

    - name: Run Multitest Script
      run: |
        cd $GITHUB_WORKSPACE/speedtest
        bash ./multi_test.sh
        bash ./fofa.sh

    - name: Update Results
      run: |
        cd $GITHUB_WORKSPACE/speedtest
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update results" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
